### ISSUE TITLE
Applus

### ISSUE THREAD

**Issue by n1ngu** [OSM-Catalan/attributions#10]
📢 **Applus**  
Portal mòbil de cita prèvia per ITV: cap atribució

**Descripció**
El mapa no és accessible directament, cal iniciar un procés de cita prèvia, omplir certa informació sobre un vehicle i aleshores NO escollir centre sinó requerir trobar el més proper per ubicació.

https://aibs.appluscorp.com/Mobile/ReservaMobile/

- S'envia la comunicació tipus del README traduïda al castellà mitjançant el formulari web de contacte https://www.applus.com/global/es/contact-us/form/ a dia 29/07/2021.

**Comment by jqngarcia** [comment]
Se envia petició al canal etic

**Comment by jlinfante** [comment]
Han afegit l'atribució.
