### ISSUE TITLE
About this repo

### ISSUE THREAD

**Issue by ghost** [OSM-Catalan/attributions#14]
Hi @yopaseopor ! 👋
Just two « requests » :

1. We updated the osm-fr issue templates, removing the old markdown templates and replacing them with new YAML proposed by GitHub. Feel free to give it a try, hope that will help your for new issues in osm-catalan repo !
2. I've opened an issue regarding to https://cityrestaurantes.es that is using OpenStreetMap FR tiles without attribution. Tho, I didn't contacted them simply because my Spanish is only at his best with Google Translate. I wonder if someone from your local community can take the case ?
  https://github.com/osm-fr/attributions/issues/168
  (I've opened an issue regarding to the French website – https://github.com/osm-fr/attributions/issues/167)

Thank you, good evening ! 😉
– Antonin

**Comment by jqngarcia** [comment]
HI @AntoninCurtit the web https://cityrestaurantes.es/ is down, can you close issue
