### ISSUE TITLE
TwoNav website shows OSM maps without attribution

### ISSUE THREAD

**Issue by opk12** [OSM-Catalan/attributions#15]
**Descripció**

Hello. This website shows OSM maps without attribution. 

- [Here](https://www.twonav.com/en/maps/spain) click `Search location` at the left
- [Here](https://www.twonav.com/en/maps/spain-topo-zones-norte) click `View location` at the right

I am talking about the website, not the sold products.

**Comment by ghost** [comment]
ADIF website (the Spanish railway infrastructure administrator) do not show OSM attribution. For example

www.adif.es/w/71801-barcelona-sants
https://www.adif.es/w/04040-zaragoza-delicias

**Comment by jqngarcia** [comment]
Modificat correctament
