### ISSUE TITLE
Botiguesobertes.cat - Falta d'atribució

### ISSUE THREAD

**Issue by yopaseopor** [OSM-Catalan/attributions#6]
📢 **Falta atribució botiguesobertes.cat**  
  `Catalunya`  
  `Mapes sense atribució`  
  `...`

**Botigues obertes va sorgir durant la COVID per donar resposta al repartiment a domicili de petites i mitjanes botigues**
https://botiguesobertes.barcelona

- Mail enviat el 28/07/2021 a info@botiguesobertes.barcelona

**Comment by jqngarcia** [comment]
Ja es correcte
